geology:
  background:
    conductivity: 0.01

  sphere:
    radius:
      min: 2.0
      max: 15.0
    conductivity:
      min: 0.005
      max: 0.2
    center:
      margin_x: 10.0
      margin_y: 10.0
      min_depth: 3.0
      max_depth: 40.0
