survey:
  # Gaussian source approximation parameter
  # Controls the spread of the injected current to avoid numerical singularities
  # A good rule of thumb is 1-2 times the cell size adjacent to the electrode.
  epsilon: 2.5

  # Base survey grid configuration
  electrode_spacing_x: 2.0  # meters
  electrode_spacing_y: 4.0  # meters
  num_electrodes_x: 21      # 40 meters total length in X
  num_lines: 5              # 16 meters total length in Y
  
  # Arrays to generate sequences for
  # Supported: wenner, schlumberger, dipole-dipole, pole-dipole
  arrays:
    wenner:
      active: false
    schlumberger:
      active: false
    dipole_dipole:
      active: true
      max_n: 8
      a_max: 6
    pole_dipole:
      active: false
      max_n: 8
      pole_distance: 1000.0  # Distance to infinity pole in meters
