"""Inspect trained PINN weights saved by the training/inversion scripts."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import torch
from torch import Tensor


PROJECT_ROOT = Path(__file__).resolve().parents[1]


def _load_checkpoint(path: Path) -> dict[str, Any]:
    try:
        checkpoint = torch.load(path, map_location="cpu", weights_only=False)
    except TypeError:
        checkpoint = torch.load(path, map_location="cpu")

    if not isinstance(checkpoint, dict):
        raise TypeError(f"Expected checkpoint dictionary, got {type(checkpoint).__name__}")
    return checkpoint


def _tensor_stats(tensor: Tensor) -> dict[str, object]:
    flat = tensor.detach().cpu().to(torch.float64).reshape(-1)
    if flat.numel() == 0:
        return {
            "shape": list(tensor.shape),
            "numel": 0,
        }

    return {
        "shape": list(tensor.shape),
        "numel": int(flat.numel()),
        "mean": float(torch.mean(flat).item()),
        "std": float(torch.std(flat, unbiased=False).item()),
        "min": float(torch.min(flat).item()),
        "max": float(torch.max(flat).item()),
        "l2_norm": float(torch.linalg.vector_norm(flat).item()),
    }


def _state_dict_summary(state_dict: dict[str, Tensor]) -> dict[str, object]:
    layer_stats = {}
    total_parameters = 0

    for name, tensor in state_dict.items():
        if not isinstance(tensor, Tensor):
            continue
        layer_stats[name] = _tensor_stats(tensor)
        total_parameters += int(tensor.numel())

    return {
        "total_tensors": len(layer_stats),
        "total_parameters": total_parameters,
        "layers": layer_stats,
    }


def inspect_checkpoint(checkpoint_path: Path) -> dict[str, object]:
    checkpoint = _load_checkpoint(checkpoint_path)

    summary: dict[str, object] = {
        "checkpoint": str(checkpoint_path),
        "mode": checkpoint.get("mode"),
        "device": checkpoint.get("device"),
        "dtype": checkpoint.get("dtype"),
        "source_electrode": checkpoint.get("source_electrode"),
        "sink_electrode": checkpoint.get("sink_electrode"),
        "networks": {},
    }

    networks = summary["networks"]
    if not isinstance(networks, dict):
        raise TypeError("Unexpected summary shape")

    for key in ("u_theta", "sigma_phi"):
        state = checkpoint.get(key)
        if isinstance(state, dict):
            networks[key] = _state_dict_summary(state)

    if not networks:
        tensor_state = {key: value for key, value in checkpoint.items() if isinstance(value, Tensor)}
        networks["checkpoint_tensors"] = _state_dict_summary(tensor_state)

    return summary


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Inspect saved PINN checkpoint weights")
    parser.add_argument(
        "--checkpoint",
        type=str,
        default=str(PROJECT_ROOT / "outputs" / "exp_default" / "checkpoints" / "invert_model.pt"),
        help="Path to a .pt checkpoint generated by training or inversion",
    )
    parser.add_argument(
        "--save-json",
        type=str,
        default=None,
        help="Optional path to save the inspection summary as JSON",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    checkpoint_path = Path(args.checkpoint)
    if not checkpoint_path.exists():
        raise FileNotFoundError(f"Checkpoint not found: {checkpoint_path}")

    summary = inspect_checkpoint(checkpoint_path)
    rendered = json.dumps(summary, indent=2)
    print(rendered)

    if args.save_json:
        output_path = Path(args.save_json)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(rendered + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
